# Import Dependency: Numpy

In [1]:
import numpy as np

# Function to generate Gaussian random variables

In [2]:
def generate_gaussian_random_variables(mu_list, sigma_list):
    random_variables = [np.random.normal(mu, sigma, k) for mu, sigma in zip(mu_list, sigma_list)]
    return random_variables

# Function to compute correlation and covariance matrices

In [3]:
def correlation_matrix(random_variables):
    N = len(random_variables)
    k = len(random_variables[0])  # Assuming all random variables have the same number of samples
    corr_matrix = np.zeros((N, N))

    for i in range(N):
        for j in range(N):
            corr_matrix[i, j] = np.mean(random_variables[i] * random_variables[j])

    return corr_matrix

def covariance_matrix(random_variables):
    N = len(random_variables)
    k = len(random_variables[0])  # Assuming all random variables have the same number of samples
    cov_matrix = np.zeros((N, N))

    for i in range(N):
        for j in range(N):
            cov_matrix[i, j] = np.mean((random_variables[i]-mu_list[i]) * (random_variables[j]-mu_list[j]))

    return cov_matrix

# Function to perform transformation of random variables

In [4]:
def transform_random_vars(random_vars, A, b):
    transformed_vars = np.dot(A, random_vars) + b[:, np.newaxis]
    return transformed_vars

# Execution with N Gaussian random variables

In [5]:
N = 3  # Number of random variables
k = 20000  # Number of samples for each random variable
mu_list = [0, 1, 2]  # List of means
sigma_list = [1, 2, 3]  # List of standard deviations

# Generate Gaussian random variables
random_vars = generate_gaussian_random_variables(mu_list, sigma_list)

# Calculate correlation matrix
corr_matrix = correlation_matrix(random_vars)
print("Correlation matrix of random variables:")
print(corr_matrix)
print('\n')

# Calculate covariance matrix
cov_matrix = covariance_matrix(random_vars)
print("Covariance matrix of random variables:")
print(cov_matrix)

Correlation matrix of random variables:
[[ 0.99172877  0.02170897 -0.03253347]
 [ 0.02170897  4.93014651  2.04402813]
 [-0.03253347  2.04402813 13.02462118]]


Covariance matrix of random variables:
[[ 0.99172877  0.02299605 -0.02995931]
 [ 0.02299605  3.93201388  0.04019812]
 [-0.02995931  0.04019812  9.00183167]]


# Execution with transformed Guassian random variables

In [8]:
# Generate random matrix A and vector b
A = np.random.rand(N, N)
b = np.random.rand(N)
print("A matrix:")
print(A)
print('\n')
print("B vector:")
print(b)
print('\n')

# Transform random variables
transformed_vars = transform_random_vars(random_vars, A, b)

# Calculate correlation matrix
corr_matrix = correlation_matrix(transformed_vars)
print("Correlation matrix of transformed random variables:")
print(corr_matrix)
print('\n')

# Calculate covariance matrix
cov_matrix = covariance_matrix(transformed_vars)
print("Covariance matrix of transformed random variables:")
print(cov_matrix)

A matrix:
[[0.14360938 0.51568587 0.04837688]
 [0.54216097 0.20204288 0.67525914]
 [0.38643988 0.39981901 0.7450892 ]]


B vector:
[0.77977432 0.4751133  0.80314687]


Correlation matrix of transformed random variables:
[[ 3.02933548  3.62503952  4.96165468]
 [ 3.62503952  8.67416766 10.53388627]
 [ 4.96165468 10.53388627 13.05909668]]


Covariance matrix of transformed random variables:
[[3.02933548 2.23321627 2.17800818]
 [2.23321627 5.61289722 5.77609719]
 [2.17800818 5.77609719 6.27302213]]


# Function to generate Exponential random variables

In [9]:
def generate_exponential_random_variables(mu_list):
    random_variables = [np.random.exponential(mu,k) for mu in mu_list] # TODO
    return random_variables

# Execution with N Exponential random variables

In [12]:
N = 4  # Number of random variables
k = 200  # Number of samples for each random variable
lambda_list = [1,2,3,4] # List of arrival rates  # TODO
mu_list = [1/i for i in lambda_list]  # List of means (What is the expected value of exponential RV?)  # TODO

# Generate Expoential random variables
random_vars = generate_exponential_random_variables(mu_list) # TODO

# Calculate correlation matrix
corr_matrix =  correlation_matrix(random_vars)# TODO
print("Correlation matrix of random variables:")
print(corr_matrix)
print('\n')

# Calculate covariance matrix
cov_matrix = covariance_matrix(random_vars) # TODO
print("Covariance matrix of random variables:")
print(cov_matrix)

Correlation matrix of random variables:
[[2.00551843 0.54200254 0.34190581 0.2549302 ]
 [0.54200254 0.52658111 0.21123163 0.14756531]
 [0.34190581 0.21123163 0.25493031 0.10179202]
 [0.2549302  0.14756531 0.10179202 0.13069369]]


Covariance matrix of random variables:
[[1.11139533 0.04949086 0.00520947 0.00190706]
 [0.04949086 0.25760021 0.02773342 0.00969121]
 [0.00520947 0.02773342 0.1298131  0.00778715]
 [0.00190706 0.00969121 0.00778715 0.06006481]]


# Execution with transformed Exponential random variables

In [13]:
# Generate random matrix A and vector b
A = np.random.rand(N, N)
b = np.random.rand(N)
print("A matrix:")
print(A)
print('\n')
print("b vector:")
print(b)
print('\n')

# Transform random variables
transformed_vars = transform_random_vars(random_vars, A, b) # TODO

# Calculate correlation matrix
corr_matrix = correlation_matrix(transformed_vars)# TODO
print("Correlation matrix of transformed random variables:")
print(corr_matrix)
print('\n')

# Calculate covariance matrix
cov_matrix = covariance_matrix(transformed_vars)# TODO
print("Covariance matrix of transformed random variables:")
print(cov_matrix)

A matrix:
[[0.71103271 0.20205407 0.1164325  0.70832885]
 [0.3698953  0.26375205 0.40449954 0.91701418]
 [0.99963539 0.12926221 0.23845827 0.38385566]
 [0.70165717 0.81679191 0.29515108 0.80029827]]


b vector:
[0.98653214 0.09682028 0.71005062 0.83373517]


Correlation matrix of transformed random variables:
[[4.60486494 2.31538385 4.64966235 5.15621346]
 [2.31538385 1.2143783  2.33809856 2.6327558 ]
 [4.64966235 2.33809856 4.80062578 5.17572664]
 [5.15621346 2.6327558  5.17572664 5.87632431]]


Covariance matrix of transformed random variables:
[[1.61558271 0.84655361 2.40756338 2.6677359 ]
 [0.84655361 0.49286862 1.2256527  1.39496974]
 [2.40756338 1.2256527  3.63803561 4.03481623]
 [2.6677359  1.39496974 4.03481623 4.81891567]]
